### PR TITLE
Add status property to meshmodels

### PR DESCRIPTION
**Pull request by Yashsharma1911**
**Description**

This PR adds a new property "ignore" in MeshModels construct which will be false by default and can be set to true to signify that a particular model should be ignored and this property can be set by the user.

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
Please change to `status`

**Comment by leecalcote** [comment]
merge conflict

**Review by leecalcote — CHANGES_REQUESTED** [review]
Must be schema-driven. A PR and release of meshery/schemas must be done first.

**Comment by leecalcote** [comment]
> Must be schema-driven. A PR and release of meshery/schemas must be done first.

@MUzairS15 will you ensure that this happens?

**Comment by Yashsharma1911** [comment]
> Must be schema-driven. A PR and release of meshery/schemas must be done first.

@leecalcote https://github.com/meshery/schemas/pull/50

**Comment by leecalcote** [comment]
Please don’t use the meshmodels term any longer.

**Pull request merged**
