### PR TITLE
Model import update

### PR DESCRIPTION
**Pull request by Jougan-0**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Jougan-0** [comment]
@MUzairS15 looked at various OCI verification one needs blob that we are not generating from export command.

**Review by humblenginr — COMMENTED** [review]
Looks good. Can we just remove the `GetById` method altogether and have that feature in the `Get` method itself?

**Comment by Jougan-0** [comment]
> Looks good. Can we just remove the `GetById` method altogether and have that feature in the `Get` method itself?

I tried using `Get` it was causing some issue we can do that in new PR.

**Comment by humblenginr** [comment]
Alright

**Review by humblenginr — APPROVED** [review]

**Comment by humblenginr** [comment]
Let's track that in an issue? @Jougan-0

**Pull request merged**
