### PR TITLE
Add go.mod sync utility

### PR DESCRIPTION
**Pull request by Revolyssup**
Signed-off-by: ashish <ashishjaitiwari15112000@gmail.com>

**Description**

This PR adds go mod syncing utility

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Revolyssup** [comment]
I have tested on few cases. Will do some final tests tomorrow and then we can merge it.

**Comment by leecalcote** [comment]
Good. Please do document your test cases here, if you would. 

https://github.com/meshery/meshkit/runs/7844991981?check_suite_focus=true#step:4:79

**Comment by leecalcote** [comment]
The immediate use case for this synchronization is between two repos. I expected a script in a workflow, but understand if dealing with text manipulation is more natural to you in golang.

**Comment by Revolyssup** [comment]
> The immediate use case for this synchronization is between two repos. I expected a script in a workflow, but understand if dealing with text manipulation is more natural to you in golang.

This utility function can be called from a workflow. After testing and merging this, second step will be to create a workflow in meshery/meshery which calls this one. We can checkout meshery-extensions repo and sync in the workflow.

**Comment by leecalcote** [comment]
All reasonable justifications for this approach. 👍

**Review by theBeginner86 — APPROVED** [review]
Works well!
LGTM

**Comment by theBeginner86** [comment]
Just one nitpick, it seems to introduce some irregular spacing. 
Though this doesn't affect anything as our `make` scripts includes `go mod tidy` which fixes it at the end.

go mod (for meshery-extension):
Screenshot 2022-09-03 at 1 42 06 AM


go mod (for meshery):
Screenshot 2022-09-03 at 1 42 25 AM

**Comment by Revolyssup** [comment]
> Just one nitpick, it seems to introduce some irregular spacing. Though this doesn't affect anything as our `make` scripts includes `go mod tidy` which fixes it at the end.
> 
> go mod (for meshery-extension): Screenshot 2022-09-03 at 1 42 06 AM
> 
> go mod (for meshery): Screenshot 2022-09-03 at 1 42 25 AM

I think we can ignore that spacing issue on the comment

**Comment by l5io** [comment]
Task linked: [CU-2q9n6d9 Add utility in Meshkit](https://app.clickup.com/t/2q9n6d9)

**Comment by Revolyssup** [comment]
@leecalcote  This PR is merged. WIll be adding the workflow now.

**Comment by leecalcote** [comment]
Good deal.

**Pull request merged**
