### PR TITLE
fix release tag function to work with alphanumeric tags  w/signoff

### PR DESCRIPTION
**Pull request by Jougan-0**
**Description**
The old function only works for numeric values and sort them. This function sorts tags based on release time rather than tag number.

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Jougan-0** [comment]
https://github.com/meshery/meshery/issues/11598

**Comment by leecalcote** [comment]
@Jougan-0 where did we land on this approach?

**Comment by Jougan-0** [comment]
> @Jougan-0 where did we land on this approach?

I was working solely on the migration and fixing bugs of the v1beta1 pr now that's done I'll head to this issue.

**Comment by leecalcote** [comment]
@Jougan-0 thank you. I'll put the k6 model to use immediately, when this is completed.

**Review by hamza-mohd — COMMENTED** [review]
Was a decision arrived at in terms of when to incorporate consideration of release date vs. tag numbering?

**Review by hamza-mohd — APPROVED** [review]
Eliminated merge conflicts.

**Comment by Jougan-0** [comment]
> Was a decision arrived at in terms of when to incorporate consideration of release date vs. tag numbering?

Nope haven't been to discuss this needs a revisit later this week if we don't stuck on Kanvas.

**Pull request closed without merging**
