### PR TITLE
Add counts to model, relationship and component

### PR DESCRIPTION
**Pull request by abdullah1308**
**Description**

This PR add the ability to get counts for models, relationships and components. This is done to support https://github.com/meshery/meshery/issues/7651

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
Do we have a REST API docs update to accompany this?

**Comment by abdullah1308** [comment]
> Do we have a REST API docs update to accompany this?

@leecalcote after I make the changes to the server endpoints, I'll make the corresponding docs update

**Comment by leecalcote** [comment]
> > Do we have a REST API docs update to accompany this?
> 
> @leecalcote after I make the changes to the server endpoints, I'll make the corresponding docs update

Sounds real good.

**Comment by Abhishek-kumar09** [comment]
@abdullah1308 Did you make sure meshery-server runs perfectly after these changes?

**Comment by Abhishek-kumar09** [comment]
are there any changes pending in meshery/meshery as well, from your side?

**Comment by abdullah1308** [comment]
> are there any changes pending in meshery/meshery as well, from your side?

@Abhishek-kumar09 yes I'll put up a PR for those in a bit

**Comment by Abhishek-kumar09** [comment]
Okay, then it needs to be reverted for now, because the changes are stopping mesher-server from starting.

**Comment by leecalcote** [comment]
@abdullah1308 with that PR having been reverted, you can now open up a new PR with that code and incorporate new changes.

**Pull request merged**
