### PR TITLE
kubectl describe equivalent in meshkit

### LINKED ISSUE #143: MeshKit support for equivalent of `kubectl describe`
**Current Behavior**

**Desired Behavior**

At ~the 30 second mark, the cursor invokes the "Describe" button and the user is presented a `kubectl describe` of the currently selected object - [drive.google.com/open?id=1tLEdJZ1L2o9I2oCKcyl9ydGLGrN4yBiB
](drive.google.com/open?id=1tLEdJZ1L2o9I2oCKcyl9ydGLGrN4yBiB)

---
**Resources**

**Alternatives / Additional Context**

### PR DESCRIPTION
**Pull request by piyushsingariya**
**Description**

This PR fixes #143

**Notes for Reviewers**
This PR deals with adding a describe function equivalent to kubectl, Instead of the raw implementation of getting details with client-go, meshkit directly uses functions from kubectl to generate details similar to `kubectl describe`

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Ready for review?

**Comment by piyushsingariya** [comment]
> Ready for review?

I'll update once it is.

**Comment by piyushsingariya** [comment]
PR is ready to be reviewed!

**Comment by leecalcote** [comment]
This enhancement meets the feature request of "a common function to describe Kubernetes objects". 

@layer5io/adapter-maintainers what tradeoffs should we be concerned with between use of client-go and kubectl library?

**Comment by piyushsingariya** [comment]
> @piyushsingariya I'm uneasy about use of `k8s.io/kubectl` is there a strong reason for not staying with the existing client-go?

ahhm, how do I say it beautifully? What I was about to write with client-go, and format it on my own, and do all the stuff, these functions do exactly same, and the fact they are exported from the package, I saw it as a bonus, and more and more type of describing function would be easy to add as our requirements increase.

**Comment by piyushsingariya** [comment]
> @piyushsingariya I'm uneasy about use of `k8s.io/kubectl` is there a strong reason for not staying with the existing client-go?

okay I was doing this because all describe functions were exported and it was saving us a big-time not writing that much code, but now that I tried to add support for more k8s resources to our code, I found inconsistencies with their code implementation, and that is so bad, I mean what's point to export structs and functions if I can't re-use them.

Now I have two options, I go on a rampage and clone the code from kubectl to meshkit for exact detail behavior or I write functions myself to fetch and write details, starting with minimum details, and with our tiny steps, we keep improving/adding more details with time.

what do you say??

**Comment by piyushsingariya** [comment]
Any reviews??

**Comment by jbyers19** [comment]
@piyushsingariya, I'm a bit confused as to why we're duplicating perfectly good code. Why not just import kubectl directly instead of rewriting this functionality?

**Comment by piyushsingariya** [comment]
> Why not just import kubectl directly instead of rewriting this functionality?

In the code of kubectl describe, there's a different `describer` struct and `Describe` method to that describer for each of k8s resources. Now the deal is with the inconsistencies of the code with kubectl describe files, all of those structs and functions are exported but I can only use few of them, and execute through meshkit.

for e.g. I can execute pod, namespace, service, job describer but I won't be able to run the deployments, statefulset, daemonset describer, etc. because the properties/fields of those describer structs aren't exported(struct is exported but not the fields).

**Comment by jbyers19** [comment]
Ah, I see. Thanks for the explanation. This looks good to me.

**Review by jbyers19 — APPROVED** [review]

**Comment by piyushsingariya** [comment]
PR is ready to be reviewed again.

**Review by leecalcote — APPROVED** [review]
LGTM. It'll be nice to be able to put these to use.

**Comment by leecalcote** [comment]
Fixing missing go.mod references

**Pull request merged**
