### PR TITLE
update rjsf gird schema for upload method left side

### PR DESCRIPTION
**Pull request by amitamrutiya**
**Description**

This PR fixes [this discussion](https://layer5io.slack.com/archives/G01BD9056TD/p1724348283333319?thread_ts=1724348174.542299&cid=G01BD9056TD)

**Notes for Reviewers**
Screenshot from 2024-08-29 10-27-02

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by sudhanshutech — CHANGES_REQUESTED** [review]
@amitamrutiya we are using schema from sistent so fixing here will not do the fix. You have fto make the change in sistent

**Comment by amitamrutiya** [comment]
Yes @sudhanshutech, you are right.

The schema used on this page, https://playground.meshery.io/configuration/designs, is from Sistent.

However, the schema used on the MeshMap page import design is from this schema. I have updated the import model schema accordingly.

**Review by leecalcote — APPROVED** [review]
We're in need of consolidating UI Schemas to a single location.

**Comment by Yashsharma1911** [comment]
> Yes @sudhanshutech, you are right.
> 
> The schema used on this page, https://playground.meshery.io/configuration/designs, is from Sistent.
> 
> However, the schema used on the MeshMap page import design is from this schema. I have updated the import model schema accordingly.

@amitamrutiya This is a regression issue, why is this happening now? have we made any changes in RJSF core components?

This schema change should not be needed

**Comment by amitamrutiya** [comment]
Yeah, @Yashsharma1911  you are right. I am not aware that this is a regression issue. Thanks for pointing out. There are definitely some component changes to make this happen.

**Pull request closed without merging**
