### PR TITLE
Change logic in whitespace formatter

### PR DESCRIPTION
**Pull request by Revolyssup**
Signed-off-by: ashish <ashishjaitiwari15112000@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Revolyssup** [comment]
@leecalcote  I will merge this tomorrow after I am 100% sure that there is nothing more to add here.

**Comment by leecalcote** [comment]
Do we have a whitelist dictionary, yet?

**Comment by Revolyssup** [comment]
> Do we have a whitelist dictionary, yet?

Not yet

**Comment by leecalcote** [comment]
Along similar lines (thinking of MeshSync as a whitelisted word), does the capabilities API support core vs non-core designation for each component? 

@Revolyssup will you file a MeshKit enhancement for @sudo-NithishKarthik consider this use case during component generation, if it is not already supported?

**Pull request merged**
