### PR TITLE
New return types to RegisterEnity and New errror codes

### PR DESCRIPTION
**Pull request by Jougan-0**
**Description**

This PR fixes #

**Notes for Reviewers**
New return types added so that can verify if the Registry error was because of model or registrant for the particular entity 
Few new error codes too.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Jougan-0** [comment]
@Yashsharma1911 @MUzairS15 please review here the old pr was causing issue with the release

**Comment by leecalcote** [comment]
@Jougan-0 will you address the failed lint checks?

**Comment by leecalcote** [comment]
@Jougan-0 provide a more description PR title, please.

**Comment by Jougan-0** [comment]
> @Jougan-0 will you address the failed lint checks?

It's now my code error i guess becuase other pr have the linting error as well .
If you want me to look why the linting error is caused I'll am looking into it .
Currently I am studying the CKA and models so that I can create a proposal for the Gsoc issue .

**Comment by Jougan-0** [comment]
https://github.com/meshery/meshery/pull/10567

**Comment by vishalvivekm** [comment]
@Jougan-0 Let's discuss this in Meshery dev call today. Add this as an agenda item to the meeting[ minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#), if you would :)

**Pull request closed without merging**
