### PR TITLE
Replace app.Convert with copy pasta Kompose

### PR DESCRIPTION
**Pull request by nicholasjackson**
**Description**

Replace log.Fatal in the Kompose app package by coping the logic from `app.Convert` and replacing `log.Fatalf` with correct error handling.

**Notes for Reviewers**
This code is not tested, however it does build

Fixes https://github.com/meshery/meshery/issues/5944

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Fixes https://github.com/meshery/meshery/issues/5944

**Review by Revolyssup — APPROVED** [review]

**Comment by Revolyssup** [comment]
@nicholasjackson  Since we are using our own fork, I think this logic should go here https://github.com/meshery/kompose

**Comment by Revolyssup** [comment]
@leecalcote  Lets go ahead with this.

**Comment by leecalcote** [comment]
Thank you, @nicholasjackson 🎈 and @Revolyssup 👍

**Comment by leecalcote** [comment]
A couple items to follow up on, but this pushes the project in a good direction.

**Pull request merged**
