### PR TITLE
Adding functions for kubeconfig file

### PR DESCRIPTION
**Pull request by piyushsingariya**
Signed-off-by: Piyush Singariya <piyushsingariya@gmail.com>

**Description**

This PR adds few functions to meshkit client to get kubeconfig and current-context in kubeconfig file

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@piyushsingariya these completely new or are we migrating and centralizing these functions from somewhere else that they reside currently?  

@Revolyssup feedback?

**Comment by piyushsingariya** [comment]
> @piyushsingariya these completely new or are we migrating and centralizing these functions from somewhere else that they reside currently?
> 
> @Revolyssup feedback?

They are new afaik.

**Comment by navendu-pottekkat** [comment]
@piyushsingariya If they are new, where are they being used currently?

**Comment by piyushsingariya** [comment]
> @piyushsingariya If they are new, where are they being used currently?

I have added them here, so that we use them in mesheryctl for getting details from kube-config, mainly the name of current-context cluster.

**Comment by leecalcote** [comment]
@piyushsingariya, no new error codes?

Are you able to confirm that the behavior in these functions meets the needs of existing functions in mesheryctl and Meshery Server and that those functions can be directly replaced? It'd be good to see a list of those functions here.

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
