### PR TITLE
updated go.mod to go v1.17 and updated dependencies

### PR DESCRIPTION
**Pull request by jbyers19**
Signed-off-by: Jared Byers <j.byers@f5.com>

**Description**

This PR updated go version to 1.17 and also updates the dependencies.

**Notes for Reviewers**
Had to update some logger references that were no longer valid after the update.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Wow. The required list of dependencies shot up quickly.

**Comment by jbyers19** [comment]
@leecalcote, yes it did. I just nuked the contents of `go.mod` and ran `go mod tidy`, and this is what it generated.

**Comment by leecalcote** [comment]
@Revolyssup feedback?

**Comment by leecalcote** [comment]
@Revolyssup any feedback on this one?

**Review by Revolyssup — APPROVED** [review]
LGTM

**Pull request merged**
