### PR TITLE
fixed Helm issue where namespace was not persisted

### PR DESCRIPTION
**Pull request by jbyers19**
Signed-off-by: Jared Byers <j.byers@f5.com>

**Description**
Updated the way the Helm action config was being created when applying Helm charts.

This PR fixes https://github.com/meshery/meshery-nginx-sm/issues/39

**Notes for Reviewers**
This change is to fix the issue where a mesh is deployed in the `meshery` namespace regardless of which namespace is specified when initiating the deploy sequence. The root cause is Helm always using the namespace provided in the initial config, which must be `meshery` because that's where mesh resources were being deployed.

Tested this change with Istio, Linkerd, and NGINX adapters and it worked as expected.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by piyushsingariya** [comment]
@jbyers19 can you also make sure that meshery installation also work as expected with mesheryctl with this update??

**Comment by jbyers19** [comment]
> @jbyers19 can you also make sure that meshery installation also work as expected with mesheryctl with this update??

Yes. I tested it and it worked.

**Review by piyushsingariya — APPROVED** [review]
CITY! 😎

**Review by alphaX86 — APPROVED** [review]
Looks good on my side 👍

**Comment by leecalcote** [comment]
> Tested this change with Istio, Linkerd, and NGINX adapters and it worked as expected.

Awesome. Thanks for running through a few of these to verify, @jbyers19

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
