### PR TITLE
[Refactor] Add `ErrorV2` struct 

### PR DESCRIPTION
**Pull request by sudo-NithishKarthik**
**Description**

 There are some limitations with the existing `Error` type:
1. There are different types of Errors. Each type of error contains different information which cannot be contained in the `Error` struct.
2. Short and Long Descriptions accept only strings and so they cannot contain structured information.
3. For example, the Validation Error information i.e. `instancePath`, `badValue`, etc. cannot be contained in the `Error` struct (or not in a structured way that the clients can make use of it).

`ErrorV2` Proposal: 
1. `ErrorV2` struct adds the ability to express all different types of errors.
2. It does so via adding a new field to the struct called `AdditionalInfo` which can contain structured error-specific information.
3. `ErrorV2` is backward compatible with the `Error` struct.

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
How does this interplay with Meshery's use of CloudEvents?

**Comment by leecalcote** [comment]
What facility, if any, does this offer to chain a set of errors together?

**Comment by leecalcote** [comment]
We're in need of a "type" and/or "category" attribute.

**Comment by sudo-NithishKarthik** [comment]
Let's use `CloudEvents`

**Comment by sudo-NithishKarthik** [comment]
Reopening this since even with `CloudEvents`, we will have to define such a structure ourselves since `CloudEvents` does not define such domain-specific things.

**Pull request merged**
