### PR TITLE
[Feat] add cue util to convert jsonschema to cue

### PR DESCRIPTION
**Pull request by sudo-NithishKarthik**
Signed-off-by: Nithish <nithishkarthik01@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
Please add appropriate labels and request review.

Lint failures need attention.

**Review by Abhishek-kumar09 — APPROVED** [review]
Lint failures are not subject to this PR's change. So approving it. Creating a new issue to adress the lint issues.

**Comment by leecalcote** [comment]
@Abhishek-kumar09 ok, sounds good.

**Comment by leecalcote** [comment]
Hopefully, we can get @sudo-NithishKarthik into a habit of returning to his PRs for follow up. 🤞 🙂

**Pull request merged**
