### PR TITLE
[Refactor] Replace `kubeopenapi-jsonschema` with CUE

### PR DESCRIPTION
**Pull request by sudo-NithishKarthik**
**Description**

This PR sets the foundation for using [CUE](https://cuelang.org/) as a central data handling component across Meshery. It replaces [`kubeopenapi-jsonschema`](https://github.com/layer5io/kubeopenapi-jsonschema) implementation with CUE. 

Instead of loading a node based binary (kubeopenapi-jsonschema) to extract the necessary information from the config files, this PR leverages the seamless integration of CUE with json and yaml, ease of conversion between CUE values and golang types and many such features to extract the necessary data that we need from the config files. This makes it faster and more efficient. 

This also makes it more flexible, since we now have the freedom to manipulate the CUE values however we want within the [`extractor`](https://github.com/meshery/meshkit/compare/nithish/cue/comp_gen?expand=1#diff-cb1ac28d323c3c4ee32bb33d20dc5a0408889ff62a5fe17d607d0450a3d8dd0eR77) functions. 

**Notes for Reviewers**

‼️ **Do not merge this PR unless the required changes are made for all the adapters** ‼️ 

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Revolyssup** [comment]
@sudo-NithishKarthik  Few lint issues to take care of

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
approved

**Comment by sudo-NithishKarthik** [comment]
lint check failures ? there are none in this pr 🤔

**Comment by leecalcote** [comment]
Oops. I was looking at an older commit. All green here. 👍

**Pull request merged**
