### PR TITLE
fix orphan go routines; add waitgroups

### PR DESCRIPTION
**Pull request by MUzairS15**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by MUzairS15** [comment]
// @leecalcote This should fix symlink/ file or directory not found errors in generations.

**Comment by leecalcote** [comment]
How many models do we expect that this fixes generation for? @Jougan-0

**Comment by Jougan-0** [comment]
> How many models do we expect that this fixes generation for? @Jougan-0

Currently, there is a difference in ```only``` one model, but there is a difference nonetheless.

**Comment by Jougan-0** [comment]
After running the Model Generator on Control (Old Meshkit) and Expermintal ( This meshkit PR)
[Control Workflow](https://github.com/Jougan-0/meshery/actions/runs/9529817300) ( 534 models)
[Experimental Workflow](https://github.com/Jougan-0/meshery/actions/runs/9530079851) (542 models)
The total amount of extra model generated are ``` 8 ```.

**Pull request merged**
