### PR TITLE
Fix go mod sync utility

### PR DESCRIPTION
**Pull request by Revolyssup**
Signed-off-by: Ashish Tiwari <ashishjaitiwari15112000@gmail.com>

**Description**

This PR fixes go mod sync utility by. removing code for copying replace statements.
`go mod tidy` is helpful for removing extra replace statements. So the utility now dumbly copies the replaced statements from source to destination and let go mod do the cleanup.

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Lint checks failing.

**Comment by acald-creator** [comment]
@leecalcote Lint is failing on the tests, coming from kompose, not us

LGTM

**Comment by leecalcote** [comment]
Argh. I wonder how long we'll have to live with this exception.

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
@Revolyssup please update the go.mod syncer section of the google doc.

**Comment by acald-creator** [comment]
> Argh. I wonder how long we'll have to live with this exception.

Not sure, I'll look into with Kompose.

**Pull request merged**
